### ISSUE TITLE
unable to read/plot dihedrals without .info file

### ISSUE THREAD

**Issue by lettis** [lettis/prodyna#7]
Hallo Katrin,
in neueren Versionen von prodyna wird ein .info-File erzeugt wenn dihedrals gebaut werden.
Dieses wird auch genutzt, wenn die dihedrals wieder eingelesen werden.
Es gibt aber viele dihedrals-Files, die mit anderen Tools oder mit einer frueheren Version von prodyna gebaut wurden, die koennen jetzt alle nicht mehr eingelesen werden.
Ich habe z.B. gerade so einen Fall.
Koenntest Du bitte einen Default einbauen (so wie in einer frueheren Version), der ohne .info funktioniert?
Ich braeuchte das relativ dringend...

Viele Gruesse,
  Florian

**Comment by sandmaennchen** [comment]
Sollte jetzt funktionieren.

**Comment by lettis** [comment]
Sehr gut, danke!
